// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxUsnKmtBQW-l7GSGJtg8CW0mKzU4mUw',
    appId: '1:484777351913:web:892dee3fe3b31fbeafee78',
    messagingSenderId: '484777351913',
    projectId: 'web-tech-final-383311',
    authDomain: 'web-tech-final-383311.firebaseapp.com',
    storageBucket: 'web-tech-final-383311.appspot.com',
    measurementId: 'G-C9ZK91YK47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo8clxcPSo4YbKKmLk5D6ryA39pJgw0JI',
    appId: '1:484777351913:android:02ba1ccfc0b85627afee78',
    messagingSenderId: '484777351913',
    projectId: 'web-tech-final-383311',
    storageBucket: 'web-tech-final-383311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtPKSmdfXfcEAeOva4KqxmsgJgc0NXPY',
    appId: '1:484777351913:ios:eb0c481e8f9481c9afee78',
    messagingSenderId: '484777351913',
    projectId: 'web-tech-final-383311',
    storageBucket: 'web-tech-final-383311.appspot.com',
    iosClientId: '484777351913-cckf8t06o2g3j038iu2h6d8pr2g4u65h.apps.googleusercontent.com',
    iosBundleId: 'com.example.webTechFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtPKSmdfXfcEAeOva4KqxmsgJgc0NXPY',
    appId: '1:484777351913:ios:eb0c481e8f9481c9afee78',
    messagingSenderId: '484777351913',
    projectId: 'web-tech-final-383311',
    storageBucket: 'web-tech-final-383311.appspot.com',
    iosClientId: '484777351913-cckf8t06o2g3j038iu2h6d8pr2g4u65h.apps.googleusercontent.com',
    iosBundleId: 'com.example.webTechFinalFlutter',
  );
}
